graph:
  image: jakubsacha/symfony-docker:php5-dev
  links:
   - db
   - neo4j
  ports:
   - "80:80"
  volumes:
   - ../:/var/www/html
db:
  image: mysql:5.6
  ports:
     - "3306:3306"
  environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
neo4j:
  image: neo4j
  ports:
     - "7474:7474"
  volumes:
     - ../data:/data
